GET http://localhost:8000/api/counts

###

PUT http://localhost:8000/api/counts/views

###

PUT http://localhost:8000/api/counts/likes

###

POST http://localhost:8000/email
Content-Type: application/json

{
    "emailFrom": "ryo_69@hotmail.fr",
    "subject": "Email from portfolio",
    "message": " Coucou"
}

###

POST https://oauth2.googleapis.com/token
Content-Type: application/json

{
    "client_id": "977267206924-5lh3f9pp0uqjdpj2jcljontttamb9muo.apps.googleusercontent.com",
    "client_secret": "YmctmghYeDbkbir9V-CVo5fC"
}